### ISSUE TITLE
0.6.0 introduced error

### ISSUE THREAD

**Issue by forensicmatt** [omerbenamram/evtx#65] opened 2019-12-04 21:15 UTC
I get the following error in version 0.6.0 but not in 0.5.1.

```
thread 'main' panicked at 'It can only be an object or null, and null was covered', src\libcore\option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\sys_common\backtrace.rs:84
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libcore\fmt\mod.rs:1024
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\io\mod.rs:1428
   5: std::sys_common::backtrace::_print
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panicking.rs:193
   8: std::panicking::default_hook
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panicking.rs:471
  10: std::panicking::begin_panic_handler
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panicking.rs:375
  11: core::panicking::panic_fmt
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libcore\panicking.rs:82
  12: core::option::expect_failed
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libcore\option.rs:1188
  13: evtx::model::raw::BinXMLRawToken::from_u8
  14: <evtx::json_output::JsonOutput as evtx::xml_output::BinXmlOutput>::visit_open_start_element
  15: evtx::binxml::assemble::parse_tokens
  16: evtx::evtx_record::EvtxRecord::into_json_value
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  18: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
  19: rayon::iter::plumbing::Folder::consume_iter
  20: rayon::iter::plumbing::bridge_producer_consumer::helper
  21: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  22: rayon::iter::collect::special_extend
  23: rayon::iter::collect::<impl rayon::iter::ParallelExtend<T> for alloc::vec::Vec<T>>::par_extend
  24: evtxtools::evtxhandler::EvtxHandler<T>::get_attribute_mapping
  25: alloc::alloc::box_free
  26: alloc::alloc::box_free
  27: crossbeam_epoch::deferred::Deferred::new::call
  28: std::rt::lang_start_internal::{{closure}}
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\rt.rs:52
  29: std::panicking::try::do_call<closure-0,i32>
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panicking.rs:292
  30: panic_unwind::__rust_maybe_catch_panic
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libpanic_unwind\lib.rs:78
  31: std::panicking::try
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panicking.rs:270
  32: std::panic::catch_unwind
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\panic.rs:394
  33: std::rt::lang_start_internal
             at /rustc/7afe6d9d1f48b998cc88fe6f01ba0082788ba4b9\/src\libstd\rt.rs:51
  34: main
  35: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  36: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  37: BaseThreadInitThunk
  38: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Here is the logfile that caused the issue.
[E_ShadowCopy6_windows_system32_winevt_logs_Microsoft-Windows-CAPI2%4Operational.zip](https://github.com/omerbenamram/evtx/files/3923942/E_ShadowCopy6_windows_system32_winevt_logs_Microsoft-Windows-CAPI2.4Operational.zip)

**Comment by forensicmatt** [comment] 2019-12-04 21:29
Interesting, it works fine with the 0.6.0 evtx_dump using `evtx_dump.exe --separate-json-attributes -o jsonl "E_ShadowCopy6_windows_system32_winevt_logs_Microsoft-Windows-CAPI2%4Operational.evtx"`.

Maybe it is something I am doing though the library. It's just strange that it works fine for me with 0.5.1 but panics on 0.6.0 using the library.

I will see if I can pin point with example code.

**Comment by forensicmatt** [comment] 2019-12-04 21:35
I am sorry, I was not using the 0.6.0 bin. The 0.6.0 bin does error out using the following:

```
>evtx_dump.exe --separate-json-attributes -o jsonl "E_ShadowCopy6_windows_system32_winevt_logs_Microsoft-Windows-CAPI2%4Operational.evtx"
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'It can only be an object or null, and null was coveredIt can only be an object or null, and null was covered', ', src\libcore\option.rssrc\libcore\option.rs::11661166::55

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: BaseThreadInitThunk
  29: RtlUserThreadStart
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: BaseThreadInitThunk
  33: RtlUserThreadStart
```

**Comment by omerbenamram** [comment] 2019-12-05 08:47
Huh! this is a regression. I'll fix it and push 0.6.1.
Sorry about that!

**Comment by omerbenamram** [comment] 2019-12-05 09:32
Fixed with #66.
This regression was introduced because 0.6.0 is smarter about nodes that have multiple XML nodes with the same name (when converting to JSON), so some unexpected paths were hit twice in places where this shouldn't have happened.

Also changed all tests to cover this flag now.

Let me know if anything else is not working with this release :)

**Closed** 2019-12-05 09:54 UTC

**Comment by forensicmatt** [comment] 2019-12-05 15:01
Thanks! Just curious, what are garbage nodes considered?

**Comment by omerbenamram** [comment] 2019-12-05 20:12
@forensicmatt it's stuff like this.

Notice the stuff between the nodes, I think windows just ignores them, but they are there.
```
<URLCacheFlushInfo></URLCacheFlushInfo>&amp;quot&amp;<URLCacheResponseInfo></URLCacheResponseInfo> 
```
